### ISSUE TITLE
¿Porqué este va fuera del bucle?

### ISSUE THREAD

**Issue by danieeeld2** [M3RINOOOOO/Practicas-IG#1]
https://github.com/M3RINOOOOO/Practicas-IG/blob/d1a61513eb6e69d7dc579c68e62bd637a28a4574/src/vaos-vbos.cpp#L391

**Comment by danieeeld2** [comment]
Que te estaba cotilleando en codigo y yo lo he metido dentro del bucle. Dijo él algo?

**Comment by M3RINOOOOO** [comment]
si no me equivoco, hay un único vbo con identificador 0, el cual no podemos modificar. Si es único, no tiene sentido tener que inicializarlo más de una vez. PD:no tengo ni idea de si el código está correcto xd

**Comment by danieeeld2** [comment]
PD:Yo tampoco jajaja
